name: Trigger auto deployment for yussugi-nextjs-shop

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/yussugi-nextjs-shop-AutoDeployTrigger-9736102f-455b-4590-bd10-689553190766.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: yussugi.azurecr.io
          username: ${{ secrets.YUSSUGINEXTJSSHOP_REGISTRY_USERNAME }}
          password: ${{ secrets.YUSSUGINEXTJSSHOP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: yussugi.azurecr.io/yussugi-nextjs-shop:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.YUSSUGINEXTJSSHOP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n yussugi-nextjs-shop -g web-app-dev --server yussugi.azurecr.io --username  ${{ secrets.YUSSUGINEXTJSSHOP_REGISTRY_USERNAME }} --password ${{ secrets.YUSSUGINEXTJSSHOP_REGISTRY_PASSWORD }}
            az containerapp update -n yussugi-nextjs-shop -g web-app-dev --image yussugi.azurecr.io/yussugi-nextjs-shop:${{ github.sha }}
